pub const GENERATORS: &[(&str, &str)] = &[
    ("abstract-noun", include_str!("abstract-noun.perchance")),
    ("animal", include_str!("animal.perchance")),
    ("archaic-word", include_str!("archaic-word.perchance")),
    ("body-part", include_str!("body-part.perchance")),
    ("color", include_str!("color.perchance")),
    ("color-name", include_str!("color-name.perchance")),
    ("common-noun", include_str!("common-noun.perchance")),
    ("concrete-noun", include_str!("concrete-noun.perchance")),
    ("country", include_str!("country.perchance")),
    ("dinosaur", include_str!("dinosaur.perchance")),
    ("emotion", include_str!("emotion.perchance")),
    (
        "endangered-animal",
        include_str!("endangered-animal.perchance"),
    ),
    (
        "english-town-name",
        include_str!("english-town-name.perchance"),
    ),
    ("fruit", include_str!("fruit.perchance")),
    ("greek-god", include_str!("greek-god.perchance")),
    ("greek-monster", include_str!("greek-monster.perchance")),
    ("greek-titan", include_str!("greek-titan.perchance")),
    ("ingredient", include_str!("ingredient.perchance")),
    ("land-animal", include_str!("land-animal.perchance")),
    ("monster-edited", include_str!("monster-edited.perchance")),
    ("monster-type", include_str!("monster-type.perchance")),
    ("nationality", include_str!("nationality.perchance")),
    ("nautical-term", include_str!("nautical-term.perchance")),
    (
        "netflix-category",
        include_str!("netflix-category.perchance"),
    ),
    ("noun", include_str!("noun.perchance")),
    ("object", include_str!("object.perchance")),
    ("occupation", include_str!("occupation.perchance")),
    (
        "person-adjective",
        include_str!("person-adjective.perchance"),
    ),
    ("planet-name", include_str!("planet-name.perchance")),
    ("room-type", include_str!("room-type.perchance")),
    ("sci-fi-noun", include_str!("sci-fi-noun.perchance")),
    (
        "simple-gen-footer",
        include_str!("simple-gen-footer.perchance"),
    ),
    ("terrain", include_str!("terrain.perchance")),
    (
        "type-of-art-edited",
        include_str!("type-of-art-edited.perchance"),
    ),
    (
        "uncountable-noun",
        include_str!("uncountable-noun.perchance"),
    ),
    ("unusual-animal", include_str!("unusual-animal.perchance")),
    ("vegetable", include_str!("vegetable.perchance")),
    ("venue", include_str!("venue.perchance")),
];
